import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "기억을 남기는 더치페이! 나누지!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}> 
        <header className="fixed top-0 left-0 w-full bg-white/90 border-b border-gray-200 z-50 shadow-sm">
          <nav className="max-w-5xl mx-auto flex items-center justify-between px-4 md:px-8 h-16">
            <Link href="/" className="font-bold text-black text-xl">기억을 남기는 더치페이! 나누지!</Link>
            <div className="flex gap-6 text-base font-medium">
              <Link href="/contact" className="hover:text-blue-600 transition">문의하기</Link>
              <Link href="/faq" className="hover:text-blue-600 transition">FAQ</Link>
              <Link href="#support" scroll={true} className="hover:text-blue-600 transition">고객센터</Link>
            </div>
          </nav>
        </header>
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
